### ISSUE TITLE
Text editing broken with proportional font

### ISSUE THREAD

**Issue by VulumeCode** [thunderclient/thunder-client-support#1499]
**Describe the bug**
When using a proportional font as editor.fontFamily, the text editor in Thunder Client gets buggy

**To Reproduce**
Set a proportional font in editor.fontFamily
Make a request with a body
Try to select and copypaste text in the body
The wrong characters are copypasted. 

Same thing happens in the response window.

**Expected behavior**
Be able to work with proportional font 

**Platform:** 
 - OS: Windows11
 - vscode version: 1.87.1
 - node version: 18.17.1
 - extension version: v2.19.0

**Are you using the free version/paid version/trial:**
 
Free

**Comment by rangav** [comment]
Hi @VulumeCode 

Not all custom fonts are supported, see here - https://github.com/rangav/thunder-client-support/issues/1326#issuecomment-1714123998

**Comment by rangav** [comment]
Will add a vscode setting to use default font or VS Code Editor font

**Comment by gnowland** [comment]
Is there a setting to set the font for thunder client code windows specifically instead of using the editor font family? All the request and response editors are broken for my setup :/ 
![Screenshot 2024-09-25 at 5 36 26 PM](https://github.com/user-attachments/assets/9cf1aa31-a676-455b-b4fd-69c5676a648a)
