### ISSUE TITLE
Make a clear distinction between Environments and Variables

### ISSUE THREAD

**Issue by yaugenka** [thunderclient/thunder-client-support#632]
Mixing Environments and Variables within one list (the Env tag) is quite confusing.
There should be a clear distinciton between these entities. Environment is something that you switch between like dev/stage/prod. Variables are placeholder values bound to environments and collections.  It would be better to allow creating variables from `within` collections and environments only and let to flag any variable as `secret` to prevent it from serialization.

**Comment by rangav** [comment]
Hi @yaugenka, did not understood your question.

Can you please provide a more details with examples and screenshots

**Comment by yaugenka** [comment]
`Global` and `Local` envrionments are confusing. The former stands for a true global scope environmet while the latter stands for a group of secret variables within global scope environment. The suggestion is to remove `local environment` and let flag any variable as secret both within global scope and custom environments.

**Comment by rangav** [comment]
Thanks for the feedback  @yaugenka , will review it.

**Comment by yaugenka** [comment]
Also I guess the initial idea of binding an environment to collection was actually to allow binding a group of collection scope variables, not the custom `switchable` environments.  I think that it is a rare case that a collection scope environment will be shared between different collections, one can just define global variables for that. So instead of binding switchable envrionments to collections it would be better to allow creating collection variables right within collections.

**Comment by MelGrubb** [comment]
I could be missing something, but my use case for this is much clearer. I have a request that calls to Auth0 to get a token. Because I want to use that token in later requests, I stuff it in an environment variable because I have no other mechanism that I know of to share information between requests. Now I've mutated my thunderEnvironment.json file and Git wants to check it in. It's not so much that I'm checking a token into source control that bothers me since it's going to expire within 24 hours anyway, but any time ANY of the devs on the team run the tests, they'll mutate the same file even though the thing that changed (the token) is only temporary to begin with. I'd really like somewhere to store temporary valued that _isn't_ the environment file to cut down on the commit noise if nothing else.

**Comment by rangav** [comment]
@MelGrubb you can store temporary tokens in `Local Environment`. did you try that?

**Comment by MelGrubb** [comment]
I just found that after posting. I don't know how I missed that before. Probably the same say I never noticed the "Sort using drag & drop" before today. How long has THAT been there. I've definitely _tried_ dragging and dropping settings. I guess the key is finding the magic spot between the variable name and the value.

**Comment by rangav** [comment]
sort is available from 13 July, 2021
https://github.com/rangav/thunder-client-support/releases/tag/1.7.0

**Comment by cw1934** [comment]
We also have plenty of use cases where we could leverage variables on the Collection _in addition_ to the variables on the Active Environment AND the Local Environment.  

As just one example, we have variables that we share among users.  This is so we have a known working value that is substituted into multiple requests only within that collection, which changes periodically so we need as few places as possible to update when it is changed.  This value would be consistent across all environments. Having it in the Local Environment would hide the value from being seen/used by anyone else on the team, even though it is something that all would need to access.

**Comment by cw1934** [comment]
I didn't remember(or find) the "Global Environment" when commenting yesterday.  I will be trying out global variables today to see if it will meet the need for now.  I think it would still be advantageous to have variables scoped at the Collection level, keeping them closer to only the Requests that utilize the variable instead of having it be something that anything could access.  Closest I've thought of so far is to use Global variables with a naming convention that indicates the Collection it's intended to be used in/for.

While the above described plan should work....our mindset of collection-based variables is something we leveraged previously, and requires thought on how to reimplement in TC.  While I understand that this is a different app, the real issue this presents is that we can't simply just import our Postman file and have it work.  We are creating a User Story for each project we try to move from Postman to ThunderClient in order to account for the manual adjustments that need to be made.  The smoother the import could be, the quicker our usage of TC will grow; whether it's converting how Postman did it to how TC handles it within the import, or implementing something at the same layer as Postman.

**Comment by rangav** [comment]
Collection Level Variables are possible using scripting
- To use - open collection settings or request view -> then select `Pre Run` Tab and use the `Scripting` tab
```js
tc.setVar("name", "Thunder Client", "request");
tc.setVar("baseUrl", "http://localhost:8744", "request");
```
